In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]
       

In [ ]:
type(lst)

list

In [ ]:
arr = np.array(lst)

In [ ]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
zeros = np.zeros((5,3))

In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones((6,3))

In [ ]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])