In [ ]:
import numpy as np

In [ ]:
np.random.random((3,3))

array([[0.1915497 , 0.94931617, 0.95339439],
       [0.82027759, 0.78887533, 0.87004608],
       [0.7780673 , 0.79305259, 0.17732751]])

In [ ]:
arr = np.random.random((3,3))

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:
arr = np.random.random((4,3))

In [ ]:
arr

array([[0.49587451, 0.32423578, 0.71319889],
       [0.12025477, 0.77100037, 0.67297886],
       [0.86135757, 0.35594741, 0.21921171],
       [0.25721803, 0.36828225, 0.66805896]])

In [ ]:
arr = np.reshape(arr , (3,4))

In [ ]:
arr

array([[0.49587451, 0.32423578, 0.71319889, 0.12025477],
       [0.77100037, 0.67297886, 0.86135757, 0.35594741],
       [0.21921171, 0.25721803, 0.36828225, 0.66805896]])

In [ ]:
arr = np.reshape(arr , (6,2))

In [ ]:
arr

array([[0.49587451, 0.32423578],
       [0.71319889, 0.12025477],
       [0.77100037, 0.67297886],
       [0.86135757, 0.35594741],
       [0.21921171, 0.25721803],
       [0.36828225, 0.66805896]])

In [ ]:
arr.flatten()

array([0.49587451, 0.32423578, 0.71319889, 0.12025477, 0.77100037,
       0.67297886, 0.86135757, 0.35594741, 0.21921171, 0.25721803,
       0.36828225, 0.66805896])