In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(arr + 1)
print(arr - 1)
print(arr * 5)
print(arr / 2)
print(arr ** 3)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 5 10 15 20 25 30]
[0.5 1.  1.5 2.  2.5 3. ]
[  1   8  27  64 125 216]


In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = arr + 1

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr += 1

In [ ]:
arr

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr *= 2

In [ ]:
arr

array([ 4,  6,  8, 10, 12, 14])

In [ ]:
arr.max()

14

In [ ]:
arr.min()

4

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.max(axis = 0) # Max element column-wise

array([7, 8, 9])

In [ ]:
arr.max(axis = 1) # Max element row-wise

array([3, 6, 9])

In [ ]:
arr.min(axis = 0) # Min element column-wise

array([1, 2, 3])

In [ ]:
arr.min(axis = 1) # Min element row-wise

array([1, 4, 7])

In [ ]:
arr.sum()

45