In [ ]:
import numpy as np

In [ ]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])

In [ ]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [ ]:
np.sort(arr , axis = 1, kind = 'mergesort')

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [ ]:
np.sort(arr , axis = 0, kind = 'mergesort')

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [ ]:
np.sort(arr , kind = 'mergesort')

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])