In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr[3: ]

array([4, 5, 6, 7, 8])

In [ ]:
arr[ : -3]

array([1, 2, 3, 4, 5])

In [ ]:
arr[3  :  -3] 

array([4, 5])

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
arr[ 3 , 1]

3

In [ ]:
arr[ 1: , 1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])