In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[8,7,6,5], [4,3,2,1]])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [ ]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [ ]:
arr = np.concatenate((arr1,arr2), axis = 0)

In [ ]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]), array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [ ]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]